
networks:
  nfttest-net:
    external: false


services:
  peer1:
    build:
      context: .
    volumes:
      - ./src/init.d/nftlist:/etc/init.d/nftlist
      - ./src/cron/nftlist.daily.sh:/etc/periodic/daily/nftlist.daily.sh
      - ./src/nftlist-little.sh:/usr/local/bin/nftlist-little.sh
      - ./src/test.py:/root/bin/test.py

      - ./lists:/etc/nftlists/included/predef
      - ./examples:/usr/share/nftlist
      - ./test:/root/test

    networks:
      - nfttest-net

    cap_add: ['SYS_ADMIN']
    privileged: true

  peer2:
    build:
      context: .
    volumes:
      - ./src/init.d/nftlist:/etc/init.d/nftlist
      - ./src/cron/nftlist.daily.sh:/etc/periodic/daily/nftlist.daily.sh
      - ./src/nftlist-little.sh:/usr/local/bin/nftlist-little.sh
      - ./src/test.py:/root/bin/test.py

      - ./lists:/etc/nftlists/included/predef
      - ./examples:/usr/share/nftlist
      - ./test:/root/test

    networks:
      - nfttest-net

    cap_add: ['SYS_ADMIN']
    privileged: true

